// This file contains mock data for the latest news in Ghana
export const ghanaNews = [
    {
        imageUrl: "https://static.euronews.com/articles/stories/09/39/25/34/320x180_cmsv2_cb29ae63-96d0-59e5-85ee-a8a3c578bbf4-9392534.jpg",
        title: "Ghana Parliament Passes Anti-LGBTQ+ Bill",
        date: "June 10, 2024",
        categories: "Trending, Politics",
        description: "The Ghanaian Parliament has passed the controversial anti-LGBTQ+ bill, sparking nationwide debates and international reactions.",
        readMoreUrl: "#",
    },
    {
        imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
        title: "Ghana Wins AFCON Qualifier Against Nigeria",
        date: "August 1, 2024",
        categories: "Sports, Trending",
        description: "Ghana's Black Stars secure a dramatic win over Nigeria in the AFCON qualifiers, reigniting hopes for the tournament.",
        readMoreUrl: "#",
    },
    {
        imageUrl: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80",
        title: "Accra Floods: Residents Call for Action",
        date: "July 28, 2024",
        categories: "Local, Environment",
        description: "Heavy rains cause severe flooding in Accra, prompting calls for improved drainage and infrastructure.",
        readMoreUrl: "#",
    },
    {
        imageUrl: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80",
        title: "Ghana Launches New Digital Currency",
        date: "July 15, 2024",
        categories: "Business, Technology",
        description: "The Bank of Ghana announces the launch of a new digital currency, aiming to boost financial inclusion.",
        readMoreUrl: "#",
    },
    {
        imageUrl: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=400&q=80",
        title: "Ghanaian Artist Wins International Award",
        date: "June 30, 2024",
        categories: "Culture, Arts",
        description: "Renowned Ghanaian artist receives international recognition for contributions to contemporary African art.",
        readMoreUrl: "#",
    },
    {
        imageUrl: "https://images.unsplash.com/photo-1465101178521-1e289f89c8e2?auto=format&fit=crop&w=400&q=80",
        title: "Ghana to Host African Tech Summit",
        date: "August 10, 2024",
        categories: "Technology, Events",
        description: "Accra is set to host the annual African Tech Summit, attracting innovators and investors from across the continent.",
        readMoreUrl: "#",
    },
    {
        imageUrl: "https://images.unsplash.com/photo-1508672019048-805c876b67e2?auto=format&fit=crop&w=400&q=80",
        title: "New Railway Project Launched in Kumasi",
        date: "July 20, 2024",
        categories: "Business, Local",
        description: "The government has launched a new railway project in Kumasi to improve transportation and boost local commerce.",
        readMoreUrl: "#",
    },
    {
        imageUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
        title: "Ghanaian Students Excel in International Science Olympiad",
        date: "August 5, 2024",
        categories: "Education, Trending",
        description: "A team of Ghanaian students has won multiple medals at the International Science Olympiad, showcasing academic excellence.",
        readMoreUrl: "#",
    },
    {
        imageUrl: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80",
        title: "Cape Coast Castle Restoration Completed",
        date: "July 25, 2024",
        categories: "Culture, History",
        description: "The historic Cape Coast Castle has undergone major restoration, preserving its legacy for future generations.",
        readMoreUrl: "#",
    },
    {
        imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
        title: "Ghanaian Startups Receive Funding Boost",
        date: "August 3, 2024",
        categories: "Business, Technology",
        description: "Several Ghanaian startups have received significant funding from international investors to accelerate growth and innovation.",
        readMoreUrl: "#",
    },
];
